FROM node:18

RUN npm install -g @vue/cli

WORKDIR /app/frontend

COPY package*.json ./

RUN npm init -y

RUN npm install

COPY . .

EXPOSE 8080

# Commande pour démarrer le serveur de développement Vue.js
CMD ["npm", "run", "serve"]