FROM php:8.1-apache

# Copie des dossiers/fichiers sur le conteneur
COPY .docker/php/php.ini /usr/local/etc/php/
COPY .docker/apache/000-default.conf /etc/apache2/sites-available/
COPY . /var/www/html

# Installation de bibliothèques/logiciels
RUN apt-get update \
    && apt-get install -y \
    libxml2-dev \
    libonig-dev \
    libzip-dev \
    git \
    zsh \
    unzip

# Installation extensions PDO pour MySQL et zip
RUN docker-php-ext-install dom xml mbstring pdo_mysql zip
# Installation de Composer
RUN curl -sS https://getcomposer.org/installer \
    | php -- --install-dir=/usr/local/bin --filename=composer \
    && chmod +x /usr/local/bin/composer

# Exécutez Composer pour installer les dépendances
RUN composer install

# Oh My Zsh + alias artisan
RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN echo 'alias artisan="php artisan"' >> ~/.zshrc

# Activez les modules Apache nécessaires pour Laravel
RUN a2enmod rewrite

# Redémarrez le service Apache
RUN service apache2 restart

# Spécifiez le répertoire de travail
WORKDIR /var/www/html

# Copiez le code source Laravel dans le conteneur
COPY . .

# Exposez le port 80 (Apache)
EXPOSE 80

# Commande pour lancer le serveur Apache
CMD ["apache2-foreground"]
